dz8_maket
fd1-44-17-group/kemchik pull request #12
Opened 2017-09-24 13:18 UTC by kemchik

@fd1-44-17

2017-09-27 05:20 UTC, fd1-44-17 requested changes

2017-09-27 05:20 UTC, fd1-44-17 commented on dz/dz8/maket_div/assets/css/style.css
> +    padding-bottom: 100%;
ойойо... что за padding-bottom с height?

2017-09-28 19:49 UTC, kemchik commented
@fd1-44-17 Please review. Без height теперь)

2017-09-29 05:04 UTC, fd1-44-17 approved these changes

2017-09-29 05:04 UTC, merged