Dz9
fd1-44-17-group/kemchik pull request #14
Opened 2017-09-28 19:36 UTC by kemchik

@fd1-44-17

2017-09-29 05:14 UTC, fd1-44-17 requested changes
Девушка, конечно, веснушчата и рыжа.. но зачем ее во все задания коммитить?)))

2017-09-29 05:14 UTC, fd1-44-17 commented on dz/dz9/zd3/index.html
> +    <div class="button">
Перед "отправить" должны быть круглые точки. 
Проблема с позиционированием .button:hover:after

2017-09-29 05:14 UTC, fd1-44-17 commented on dz/dz9/zd3/index.html
> +    <div class="button">
https://jsfiddle.net/anton4ept/nfw924y2/ - посмотрите, как ваш стиль смотрится здесь

2017-09-30 08:23 UTC, kemchik commented
@fd1-44-17 Please review

2017-09-30 08:24 UTC, kemchik commented
@fd1-44-17 Please review

2017-10-05 12:06 UTC, fd1-44-17 approved these changes

2017-10-05 12:06 UTC, merged