Work animal language
fd1-44-17-group/kemchik pull request #2
Opened 2017-09-04 08:20 UTC by kemchik

@fd1-44-17

2017-09-04 13:59 UTC, fd1-44-17 requested changes
работаем над ошибками

2017-09-04 13:59 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +        язык поз и телодвижений;<br>
это список, а не абзац

2017-09-04 13:59 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +        <p>Язык животных</p>
здесь тоже должен быть список.

2017-09-07 09:31 UTC, kemchik commented
@fd1-44-17 
Please review

2017-09-07 09:50 UTC, fd1-44-17 approved these changes

2017-09-07 09:50 UTC, merged