Dz2 0509
fd1-44-17-group/kemchik pull request #3
Opened 2017-09-05 10:39 UTC by kemchik

@fd1-44-17

2017-09-05 12:48 UTC, fd1-44-17 requested changes
нужно поработать над ошибками

2017-09-05 12:48 UTC, fd1-44-17 commented on dz/dz2/childbook.html
> +        <p>За рулем сижу довольный &#8212<br>
не правильно используете мнемоники

2017-09-05 12:48 UTC, fd1-44-17 commented on dz/dz2/childbook.html
> +        Только жаль &#8212 не поместиться.</p>
не правильно используете мнемоники

2017-09-05 12:48 UTC, fd1-44-17 commented on dz/dz2/dz2_2.html
> +        <p>&#169 бородатый <a href="https://www.anekdot.ru/" title="перейти" target="_blank">анекдот</a></p>
не правильно используете мнемоники

2017-09-05 12:48 UTC, fd1-44-17 commented on dz/dz2/dz2_2.html
> +        <li><strong>Четверг.</strong> Под покровом ночи смогли снова засесть в доме лесника. Курим &#171Беломор&#187.</li>
не правильно используете мнемоники

2017-09-06 05:45 UTC, kemchik commented
@fd1-44-17 
Please review

2017-09-07 06:06 UTC, fd1-44-17 requested changes
Каналы связи оформить списком.

2017-09-07 06:06 UTC, fd1-44-17 commented on work/0409/animal_language.html
> +        <p>Различают три канала связи:<br>
это все-таки список.

2017-09-07 19:07 UTC, kemchik commented
@fd1-44-17 
Please review)

2017-09-08 05:13 UTC, fd1-44-17 approved these changes

2017-09-08 05:14 UTC, merged