dz4
fd1-44-17-group/kemchik pull request #6
Opened 2017-09-12 15:30 UTC by kemchik

@fd1-44-17

2017-09-15 05:34 UTC, fd1-44-17 requested changes

2017-09-15 05:34 UTC, fd1-44-17 commented on dz/dz4/div_frame/index.html
> +    <div class="ramka">
рамку необходимо было сделать с помощью таблицы.

2017-09-17 11:59 UTC, kemchik commented
@fd1-44-17 Please review)

2017-09-17 19:20 UTC, fd1-44-17 approved these changes

2017-09-17 19:20 UTC, merged