first
fd1-44-17-group/kemchik pull request #8
Opened 2017-09-14 18:58 UTC by kemchik

@fd1-44-17 Please review

2017-09-15 05:32 UTC, fd1-44-17 requested changes

2017-09-15 05:32 UTC, fd1-44-17 commented on dz/dz5/index.html
> +        <div class="cell down right black figure lod black_figure">
обожемой. Что это за уровни вложенности фигур?

2017-09-16 08:57 UTC, kemchik commented
@fd1-44-17 Please review

2017-09-17 19:19 UTC, fd1-44-17 approved these changes

2017-09-17 19:19 UTC, merged